### ISSUE TITLE
Practica de testrail

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-teccaf#1]
[Qase.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-teccaf/files/12807216/Qase.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
